### ISSUE TITLE
Array index out-of-bounds

### ISSUE THREAD

**Issue by kilroy98** [Stewart-Anubis/Zr_Countdown_Hud#1]
SourceMod Version: 1.10.0.6502

> L 05/16/2021 - 11:50:47: [SM] Exception reported: Array index out-of-bounds (index 34, limit 33)
> L 05/16/2021 - 11:50:47: [SM] Blaming: zr_countdown_hud.smx
> L 05/16/2021 - 11:50:47: [SM] Call stack trace:
> L 05/16/2021 - 11:50:47: [SM]   [1] Line 145, zr_countdown_hud.sp::OnClientDisconnect_Post

**Comment by Stewart-Anubis** [comment]
Update ..

**Comment by kilroy98** [comment]
I installed the new version, there are no errors in the logs yet. But I'll watch the logs a little more.
If the error persists, I will reopen this issue.
